[package]
name = "word_processor"
version = "0.1.0"
authors = ["EightyS3v3n <eightys3v3n@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
